# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'fi-fi'
    sources:
      - filename: 'src/hunspell/fi_FI.dic'
      - filename: 'src/additional_words.txt'
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: false
checksumFile: true
