# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json

$schema: https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json
targets:
  - name: markdown
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - src/markdown.txt
    sort: true
