# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: '<%= packageName %>'
    sources:
      - filename: '<%= srcFile %>'
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
    format: '<%= format %>'
    targetDirectory: './dict'
    generateNonStrict: <%= generateNonStrict %>
    compress: false
checksumFile: true
