# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: en_GB
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - listFile: source-files.txt
    sort: true
    generateNonStrict: true
    excludeWordsFrom:
      - node_modules/@codetypo/dict-en-shared/src/exclude-words.txt
checksumFile: true
