# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: ada
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - src/ada.txt
    sort: true
keepRawCase: true
