# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'fsharp'
    sources:
      - src/fsharp.txt
      - src/from-fsharp-src.txt
    format: 'plaintext'
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
